openapi: 3.0.1
info:
  title: MI_PATIENT
  description: API Definition for the MI_PATIENT Synapse API (Micro Integrator)
  version: 1.0.0
servers:
  - url: http://localhost:8290/pepedoctor
  - url: https://localhost:8253/pepedoctor
paths:
  /:
    get:
      summary: Obtener listado de pacientes
      description: Devuelve un objeto con la lista de pacientes (id, name, age, diagnosis).
      operationId: getPatients
      responses:
        "200":
          description: Lista de pacientes (ÃƒÂ©xito)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatientsResponse"
              examples:
                ejemplo-pacientes:
                  summary: Respuesta ejemplo
                  value:
                    patients:
                      - id: 1
                        name: Juan PÃƒÂ©rez
                        age: 45
                        diagnosis: Diabetes
                      - id: 2
                        name: MarÃƒÂ­a LÃƒÂ³pez
                        age: 32
                        diagnosis: HipertensiÃƒÂ³n
                      - id: 3
                        name: Carlos GÃƒÂ³mez
                        age: 60
                        diagnosis: Asma
                      - id: 4
                        name: Ana MartÃƒÂ­nez
                        age: 27
                        diagnosis: MigraÃƒÂ±a
        4XX:
          description: Error de cliente
        5XX:
          description: Error de servidor
components:
  schemas:
    Patient:
      required:
        - age
        - diagnosis
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Juan PÃƒÂ©rez
        age:
          type: integer
          example: 45
        diagnosis:
          type: string
          example: Diabetes
    PatientsResponse:
      required:
        - patients
      type: object
      properties:
        patients:
          type: array
          items:
            $ref: "#/components/schemas/Patient"
