openapi: 3.0.1
info:
  title: MI_PATIENT
  description: API Definition of HealthcareAPI1
  version: 1.0.0
servers:
- url: http://localhost:8290/patients
- url: https://localhost:8253/patients
paths:
  /:
    get:
      responses:
        default:
          description: Default response
